name: app-ci-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - app/**
      - tests/**
      - pipelines/ci-pipeline.yml
      - pipelines/cd-pipeline.yml
    exclude:
      - terraform/**
      - README.md

pr:
  branches:
    include:
      - main
  paths:
    include:
      - app/**
      - tests/**

pool:
  name: self-hosted-dev

variables:
  pythonVersion: '3.10'
  banditVersion: '1.7.8'
  checkovVersion: '3.2.0'

steps:
- checkout: self
  clean: true

# ---------------------------
# Use Python
# ---------------------------
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
  displayName: "Use Python $(pythonVersion)"

# ---------------------------
# Install + Test
# ---------------------------
- script: |
    python -m pip install --upgrade pip
    pip install -r app/requirements.txt
    pip install pytest
    pytest -q --junitxml=$(Build.SourcesDirectory)/test-results.xml
  displayName: "Install dependencies and run unit tests"

- task: PublishTestResults@2
  displayName: "Publish test results"
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: "JUnit"
    testResultsFiles: "$(Build.SourcesDirectory)/test-results.xml"
    failTaskOnFailedTests: true

# ---------------------------
# Security Scan (SAST + IaC)
# ---------------------------
- script: |
    python -m pip install "bandit==$(banditVersion)" "checkov==$(checkovVersion)"
    bandit -r ./app -q
    checkov -d ./terraform --framework terraform --quiet
  displayName: "Security Scan (Bandit + Checkov)"

# ---------------------------
# Package Artifact (ONLY main)
# ---------------------------
- task: ArchiveFiles@2
  displayName: "Package app artifact (main only)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    rootFolderOrFile: 'app'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

# ---------------------------
# Publish Artifact (ONLY main)
# ---------------------------
- task: PublishPipelineArtifact@1
  displayName: "Publish artifact (main only)"
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/app.zip'
    artifact: drop