name: terraform-cd-$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: tfci
    source: terraform-ci
    trigger:
      branches:
        include:
          - main

variables:
  - group: rg-tfstate-devopspy-dev
  - name: TF_ROOT
    value: terraform/main
  - name: TF_VERSION
    value: "1.6.6"

stages:
- stage: Apply_Prod
  displayName: "Terraform Apply (Prod)"
  jobs:
  - deployment: ApplyProd
    displayName: "Apply tfplan (Prod)"
    pool:
      name: self-hosted-dev
    environment: devopspy-prod # Approval gate happens here
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - download: tfci
            displayName: "Download tfplan artifacts from CI"
            artifact: tfplan

          - task: TerraformInstaller@1
            displayName: "Install Terraform $(TF_VERSION)"
            inputs:
              terraformVersion: "$(TF_VERSION)"

          - task: AzureCLI@2
            displayName: "Azure login (OIDC) + Terraform Apply"
            inputs:
              azureSubscription: "sc-devopspy-terraform-oidc"
              scriptType: pscore
              scriptLocation: inlineScript
              addSpnToEnvironment: true
              inlineScript: |
                $ErrorActionPreference = "Stop"

                # 1. Init using the same Dynamic Config as CI
                Write-Host "==> Terraform init (Dynamic Config)"
                terraform -chdir="$(TF_ROOT)" init -reconfigure `
                  -backend-config="resource_group_name=$(TF_STATE_RG)" `
                  -backend-config="storage_account_name=$(TF_STATE_STORAGE)" `
                  -backend-config="container_name=tfstate" `
                  -backend-config="key=terraform.tfstate"

                # 2. Copy the artifact to the correct folder
                Write-Host "==> Moving plan file"
                # ADO downloads to $(Pipeline.Workspace)/{alias}/{artifactname}
                $downloadedPlan = "$(Pipeline.Workspace)/tfci/tfplan/tfplan"
                Copy-Item $downloadedPlan -Destination "$(TF_ROOT)/tfplan" -Force

                # 3. Apply the plan
                Write-Host "==> Applying Plan"
                terraform -chdir="$(TF_ROOT)" apply -input=false -auto-approve "$(TF_ROOT)/tfplan"